export type ApprovalFieldType = "text" | "textarea" | "number" | "select" | "date" | "datetime";

export interface ApprovalTemplateField {
  key: string;
  label: string;
  type?: ApprovalFieldType;
  required?: boolean;
  span?: 1 | 2;
  rows?: number;
  placeholder?: string;
  options?: string[];
  defaultValue?: string | number;
}

export interface ApprovalTemplate {
  key: string;
  label: string;
  source: string;
  defaultApplicant: string;
  defaultDepartment: string;
  defaultTitle: string;
  defaultSummary: string;
  customerField?: string;
  businessNoField?: string;
  amountField?: string;
  fields: ApprovalTemplateField[];
  nodes: Array<{ name: string; operator?: string }>;
  riskItems: string[];
  requiredAttachments?: string[];
}

const companyOptions = ["延成新能源", "能易换", "哈成"];
const payerOptions = ["我方承担", "客户承担", "厂商承担", "按合同约定"];
const yesNoOptions = ["是", "否"];
const batteryStatusOptions = ["闲置在库", "下游客户在租", "维修中", "退租验收", "待报废", "待售卖"];
const disposalOptions = ["回收入库", "买断出库", "售卖出库", "报废出库", "换新入库"];

export const approvalTemplates: ApprovalTemplate[] = [
  {
    key: "SAMPLE_DELIVERY",
    label: "送样审批",
    source: "《延成公司业务流程》样品电池送样审批单",
    defaultApplicant: "刘销售",
    defaultDepartment: "销售部",
    defaultTitle: "样品电池送样申请",
    defaultSummary: "业务员发起样品电池送样，需确认客户、厂商、型号、押金和快递费用划分。",
    customerField: "customerName",
    amountField: "depositAmount",
    fields: [
      { key: "customerName", label: "客户名称（样品接收方）", required: true },
      { key: "manufacturer", label: "电池厂商", required: true },
      { key: "model", label: "规格型号", required: true },
      { key: "sampleQuantity", label: "样品数量", type: "number", required: true, defaultValue: 1 },
      { key: "sendFreightPayer", label: "发货运费支付方", type: "select", options: payerOptions, required: true },
      { key: "returnFreightPayer", label: "收回运费支付方", type: "select", options: payerOptions, required: true },
      { key: "depositAmount", label: "样品押金", type: "number", required: true },
      { key: "depositAccount", label: "押金收款账户" },
      { key: "receiverInfo", label: "收件信息", type: "textarea", span: 2, rows: 3, required: true },
      { key: "remark", label: "备注", type: "textarea", span: 2, rows: 2 },
    ],
    nodes: [
      { name: "业务员发起送样申请", operator: "申请人" },
      { name: "刘少鹏审批", operator: "刘少鹏" },
      { name: "彭总审批", operator: "彭总" },
      { name: "资产管理员协同", operator: "资产管理员" },
      { name: "业务员跟进测试", operator: "申请人" },
      { name: "固定资产管理员处理样品去向", operator: "资产管理员" },
    ],
    riskItems: ["样品需在 7 天内出具测试结果并确认处理方式。", "快递费用归属和押金收款账户必须在发起时写清。"],
    requiredAttachments: ["客户送样需求截图", "收件信息确认"],
  },
  {
    key: "PURCHASE_REQUEST",
    label: "采购需求审批",
    source: "《延成公司业务流程》采购需求审批单",
    defaultApplicant: "王采购",
    defaultDepartment: "采购部",
    defaultTitle: "采购需求申请",
    defaultSummary: "根据客户需求或销售合同条款发起采购需求，审批后由采购对接厂商并拟定合同。",
    businessNoField: "relatedOrderNo",
    fields: [
      { key: "companyName", label: "公司名称", type: "select", options: companyOptions, required: true, defaultValue: "延成新能源" },
      { key: "reason", label: "申请事由", required: true },
      { key: "relatedOrderNo", label: "关联销售合同/订单" },
      {
        key: "purchaseItems",
        label: "采购明细",
        type: "textarea",
        span: 2,
        rows: 4,
        required: true,
        placeholder: "按行填写：物品名称 / 型号或规格 / 数量 / 期望交付日期 / 建议供应商 / 产品其他要求 / 备注",
      },
      { key: "expectedDeliveryDate", label: "期望交付日期", type: "date" },
      { key: "suggestedSupplier", label: "建议供应商" },
    ],
    nodes: [
      { name: "业务员或需求部门发起", operator: "申请人" },
      { name: "刘少鹏审批", operator: "刘少鹏" },
      { name: "彭总审批", operator: "彭总" },
      { name: "采购抄送并执行", operator: "采购" },
    ],
    riskItems: ["采购明细必须包含型号、数量、交付时间和交付标准。", "审批通过后采购需确认生产厂商、发起合同和下发采购订单。"],
    requiredAttachments: ["销售合同或客户需求确认", "产品参数要求"],
  },
  {
    key: "PURCHASE_CONTRACT",
    label: "采购合同会签",
    source: "《延成公司业务流程》采购合同审批单",
    defaultApplicant: "王采购",
    defaultDepartment: "采购部",
    defaultTitle: "采购合同审批",
    defaultSummary: "根据采购需求审批、商务条款和技术售后条款发起采购合同会签。",
    customerField: "counterparty",
    businessNoField: "contractNo",
    amountField: "contractAmount",
    fields: [
      { key: "contractType", label: "合同类型", type: "select", required: true, options: ["电池采购合同", "电柜采购合同", "零部件采购合同", "办公及其他用品采购合同"] },
      { key: "contractName", label: "合同名称", required: true },
      { key: "contractNo", label: "合同编号", required: true },
      { key: "signDate", label: "签约日期", type: "date", required: true },
      { key: "companyName", label: "公司名称", type: "select", options: companyOptions, required: true, defaultValue: "延成新能源" },
      { key: "counterparty", label: "对方单位名称", required: true },
      {
        key: "contractItems",
        label: "采购合同明细",
        type: "textarea",
        span: 2,
        rows: 4,
        required: true,
        placeholder: "按行填写：物品名称 / 规格型号 / 数量 / 采购单价 / 采购金额 / 备注",
      },
      { key: "contractAmount", label: "采购金额合计", type: "number", required: true },
      { key: "paymentTerm", label: "付款方式", type: "textarea", span: 2, rows: 3, required: true, placeholder: "例如：预付款、货到后开票、开票后付款、质保金比例" },
      { key: "relatedPurchaseRequest", label: "关联采购需求单", required: true },
    ],
    nodes: [
      { name: "采购发起", operator: "申请人" },
      { name: "财务审批", operator: "赵财务" },
      { name: "法务审批", operator: "法务" },
      { name: "技术审批", operator: "技术部" },
      { name: "刘少鹏审批", operator: "刘少鹏" },
      { name: "彭总审批", operator: "彭总" },
      { name: "行政抄送用印", operator: "行政" },
      { name: "财务/固定资产抄送", operator: "财务/资产" },
    ],
    riskItems: ["财务需审核量、价、税、费和付款条件。", "法务审核违约风险，技术审核售后质保条款。"],
    requiredAttachments: ["合同文本", "采购需求单", "报价或比价记录"],
  },
  {
    key: "PAYMENT_REQUEST",
    label: "付款申请",
    source: "《延成公司业务流程》付款申请单",
    defaultApplicant: "赵财务",
    defaultDepartment: "财务部",
    defaultTitle: "付款申请单",
    defaultSummary: "基于采购付款申请、采购合同或押金资料发起付款审批。",
    customerField: "payee",
    amountField: "paymentAmount",
    fields: [
      { key: "companyName", label: "公司", type: "select", options: companyOptions, required: true, defaultValue: "延成新能源" },
      { key: "expenseType", label: "费用类型", required: true },
      { key: "paymentTime", label: "申请支付时间", type: "datetime", required: true },
      { key: "reason", label: "付款申请事由", type: "textarea", span: 2, rows: 3, required: true },
      { key: "payee", label: "收款人", required: true },
      { key: "paymentAmount", label: "费用金额", type: "number", required: true },
      { key: "accountInfo", label: "收款账户及信息", type: "textarea", span: 2, rows: 3, required: true },
      { key: "remark", label: "备注", type: "textarea", span: 2, rows: 2, placeholder: "例如：付款时限、付款单备注" },
    ],
    nodes: [
      { name: "发起人", operator: "申请人" },
      { name: "部门负责人审核", operator: "部门负责人" },
      { name: "财务审核", operator: "赵财务" },
      { name: "刘少鹏审批", operator: "刘少鹏" },
      { name: "彭总审批", operator: "彭总" },
      { name: "出纳付款", operator: "出纳" },
    ],
    riskItems: ["付款申请需附采购合同、押金收据、收货单或对账单。", "收款账户信息和付款备注必须清晰可复核。"],
    requiredAttachments: ["采购合同", "押金收据", "收货单", "对账单"],
  },
  {
    key: "SALES_CONTRACT",
    label: "销售/租赁合同会签",
    source: "《延成公司业务流程》销售合同审批单",
    defaultApplicant: "刘销售",
    defaultDepartment: "销售部",
    defaultTitle: "销售合同审批",
    defaultSummary: "根据商务条款、技术售后条款和租赁价格发起销售或租赁合同会签。",
    customerField: "counterparty",
    businessNoField: "contractNo",
    amountField: "depositTotal",
    fields: [
      { key: "contractType", label: "合同类型", type: "select", options: ["租赁合同", "联营合同"], required: true },
      { key: "contractName", label: "合同名称", required: true },
      { key: "contractNo", label: "合同编号", required: true },
      { key: "signDate", label: "签约日期", type: "date", required: true },
      { key: "companyName", label: "公司名称", type: "select", options: companyOptions, required: true, defaultValue: "延成新能源" },
      { key: "counterparty", label: "对方单位名称", required: true },
      {
        key: "leaseItems",
        label: "租赁/销售明细",
        type: "textarea",
        span: 2,
        rows: 4,
        required: true,
        placeholder: "按行填写：物品名称 / 规格型号 / 数量 / 租赁价格 / 押金 / 买断价 / 租期",
      },
      { key: "depositTotal", label: "押金合计", type: "number" },
      { key: "renewalPrice", label: "到期后续租价格", type: "textarea", span: 2, rows: 2, placeholder: "例如：租赁期三年，三年内不得退租，三年后按年续租" },
      { key: "remark", label: "备注", type: "textarea", span: 2, rows: 2 },
    ],
    nodes: [
      { name: "合同专员发起", operator: "申请人" },
      { name: "业务负责人审批", operator: "业务负责人" },
      { name: "财务审批", operator: "赵财务" },
      { name: "法务审批", operator: "法务" },
      { name: "技术审批", operator: "技术部" },
      { name: "刘少鹏审批", operator: "刘少鹏" },
      { name: "彭总审批", operator: "彭总" },
      { name: "行政抄送用印", operator: "行政" },
      { name: "财务/固定资产抄送", operator: "财务/资产" },
    ],
    riskItems: ["财务审核量、价、税、费和付款条件。", "技术审核售后质保条款，法务审核合同风险。"],
    requiredAttachments: ["合同文本", "客户报价确认", "技术参数确认"],
  },
  {
    key: "PURCHASE_INBOUND",
    label: "采购入库申请",
    source: "《延成公司业务流程》采购入库申请单流程",
    defaultApplicant: "王采购",
    defaultDepartment: "采购部",
    defaultTitle: "采购入库申请",
    defaultSummary: "根据上游客户交货清单发起入库申请，技术审核质量后由固定资产专员入库。",
    customerField: "supplierName",
    businessNoField: "deliveryListNo",
    fields: [
      { key: "supplierName", label: "上游客户/供应商", required: true },
      { key: "deliveryListNo", label: "交货清单号", required: true },
      { key: "productInfo", label: "产品型号及数量", type: "textarea", span: 2, rows: 3, required: true },
      { key: "qualityResult", label: "技术质量审核结论", type: "textarea", span: 2, rows: 3 },
      { key: "assetSystemNo", label: "固定资产入库编号" },
      { key: "inboundDate", label: "计划入库日期", type: "date" },
    ],
    nodes: [
      { name: "采购发起", operator: "申请人" },
      { name: "技术部审核", operator: "技术部" },
      { name: "固定资产专员入库", operator: "资产管理员" },
      { name: "财务部抄送入账", operator: "财务" },
    ],
    riskItems: ["必须先审核交货产品质量，再维护固定资产系统。"],
    requiredAttachments: ["交货清单", "质量验收记录"],
  },
  {
    key: "LEASE_OUTBOUND",
    label: "租赁出库申请",
    source: "《延成公司业务流程》租赁出库申请单流程",
    defaultApplicant: "刘销售",
    defaultDepartment: "销售部",
    defaultTitle: "租赁出库申请",
    defaultSummary: "业务凭租赁合同和客户订单发起出库，资产管理员核对编码、数量和型号。",
    customerField: "customerName",
    businessNoField: "orderNo",
    fields: [
      { key: "customerName", label: "客户名称", required: true },
      { key: "contractNo", label: "关联合同编号", required: true },
      { key: "orderNo", label: "订单编号", required: true },
      { key: "assetCodes", label: "电池编码/资产编码", type: "textarea", span: 2, rows: 3, required: true },
      { key: "model", label: "规格型号", required: true },
      { key: "quantity", label: "出库数量", type: "number", required: true },
      { key: "receiverInfo", label: "收货信息", type: "textarea", span: 2, rows: 3, required: true },
      { key: "freightPayer", label: "运输费用承担方", type: "select", options: payerOptions },
    ],
    nodes: [
      { name: "业务员发起", operator: "申请人" },
      { name: "资产管理员核对出库", operator: "资产管理员" },
      { name: "技术部电池管理系统划拨", operator: "技术部" },
      { name: "财务部依据发货单入账", operator: "财务" },
    ],
    riskItems: ["资产管理员需核对编码、数量、型号并输出发货单。", "技术部需在电池管理系统完成划拨。"],
    requiredAttachments: ["租赁合同", "客户订单", "发货单"],
  },
  {
    key: "ASSET_TRANSFER",
    label: "调拨审批",
    source: "《延成公司业务流程》调拨审批流程",
    defaultApplicant: "刘销售",
    defaultDepartment: "销售部",
    defaultTitle: "电池调拨申请",
    defaultSummary: "调拨申请需写清调出地、接收地、型号、数量、租期、价格和运输费用承担方。",
    customerField: "receiveLocation",
    amountField: "rentAmount",
    fields: [
      { key: "fromLocation", label: "调出地", required: true },
      { key: "receiveLocation", label: "接收地", required: true },
      { key: "transferTime", label: "调拨时间", type: "datetime", required: true },
      { key: "model", label: "电池型号", required: true },
      { key: "quantity", label: "调拨数量", type: "number", required: true },
      { key: "dealMode", label: "收款方式", type: "select", options: ["买断", "租赁"], required: true },
      { key: "leaseTerm", label: "租赁期" },
      { key: "priceRule", label: "价格计算方式", required: true },
      { key: "rentAmount", label: "租金/费用金额", type: "number" },
      { key: "hasDeposit", label: "有无押金", type: "select", options: yesNoOptions },
      { key: "depositPayTime", label: "押金支付时间", type: "datetime" },
      { key: "freightPayer", label: "调拨运输费用承担方", type: "select", options: payerOptions, required: true },
    ],
    nodes: [
      { name: "业务员发起调拨申请", operator: "申请人" },
      { name: "技术部审核", operator: "技术部" },
      { name: "彭总审批", operator: "彭总" },
      { name: "固定资产管理员协同", operator: "资产管理员" },
      { name: "技术/财务抄送", operator: "技术/财务" },
    ],
    riskItems: ["技术需检查调出地电池性能状态并判断型号参数是否匹配。", "审批通过后资产系统需输出调拨清单。"],
    requiredAttachments: ["调拨清单", "双方合同或订单"],
  },
  {
    key: "FACTORY_REPAIR",
    label: "返厂维修申请",
    source: "《延成公司业务流程》返厂维修申请单流程",
    defaultApplicant: "赵工",
    defaultDepartment: "售后技术部",
    defaultTitle: "返厂维修申请",
    defaultSummary: "售后发起返厂维修，技术判断质保期和维修方案，资产系统同步维修状态。",
    customerField: "customerName",
    businessNoField: "faultNo",
    fields: [
      { key: "faultNo", label: "故障提报单号", required: true },
      { key: "customerName", label: "客户/来源", required: true },
      { key: "assetCode", label: "电池编码/BT码", required: true },
      { key: "faultDesc", label: "故障描述", type: "textarea", span: 2, rows: 3, required: true },
      { key: "warrantyStatus", label: "是否质保期内", type: "select", options: yesNoOptions, required: true },
      { key: "repairPlan", label: "维修方案", type: "select", options: ["维修后返还客户", "维修后返还至公司", "厂商更换电池", "更换备用电池给客户"], required: true },
      { key: "logisticsInfo", label: "返厂物流信息", type: "textarea", span: 2, rows: 2 },
    ],
    nodes: [
      { name: "售后发起返厂维修申请", operator: "申请人" },
      { name: "技术审核", operator: "技术部" },
      { name: "售后物流发出确认", operator: "售后物流" },
      { name: "固定资产审核", operator: "资产管理员" },
      { name: "技术协同厂商沟通", operator: "技术部" },
      { name: "售后物流收回确认", operator: "售后物流" },
      { name: "固定资产处理", operator: "资产管理员" },
    ],
    riskItems: ["返厂审核需判断是否在质保期内。", "维修完成后必须同步固定资产系统状态。"],
    requiredAttachments: ["故障提报", "检测记录", "物流凭证"],
  },
  {
    key: "DAMAGE_COMPENSATION",
    label: "人为损坏赔偿",
    source: "《延成公司业务流程》人为损坏索赔审批流程",
    defaultApplicant: "赵工",
    defaultDepartment: "售后技术部",
    defaultTitle: "人为损坏赔偿申请",
    defaultSummary: "技术部根据故障报修和返修检测报告出具鉴定单，并按合同条款发起索赔。",
    customerField: "customerName",
    amountField: "claimAmount",
    fields: [
      { key: "customerName", label: "客户名称", required: true },
      { key: "faultNo", label: "故障/返修单号", required: true },
      { key: "assetCode", label: "电池编码/BT码", required: true },
      { key: "damageConclusion", label: "人为损坏鉴定结论", type: "textarea", span: 2, rows: 3, required: true },
      { key: "contractClause", label: "合同赔付条款", type: "textarea", span: 2, rows: 2, required: true },
      { key: "claimAmount", label: "索赔金额", type: "number", required: true },
      { key: "disposalMethod", label: "废旧电池处置方式", type: "select", options: disposalOptions, required: true },
      { key: "receiptNo", label: "赔付收款单号" },
    ],
    nodes: [
      { name: "技术部发起", operator: "申请人" },
      { name: "业务员审核赔付条款", operator: "业务员" },
      { name: "财务审核赔付金额", operator: "赵财务" },
      { name: "彭总审批赔偿标准", operator: "彭总" },
      { name: "资产管理员/财务执行", operator: "资产/财务" },
    ],
    riskItems: ["赔偿标准必须有检测报告和合同条款支撑。", "需明确旧电池回收入库或买断出库的后续处理。"],
    requiredAttachments: ["人为损坏鉴定单", "返修检测报告", "合同条款截图"],
  },
  {
    key: "CUSTOMER_RETURN",
    label: "客户退租审批",
    source: "《延成公司业务流程》客户退租审批流程",
    defaultApplicant: "刘销售",
    defaultDepartment: "销售部",
    defaultTitle: "客户退租申请",
    defaultSummary: "业务说明退租原因和数量，技术验收电池状态后确认退还押金或索赔金额。",
    customerField: "customerName",
    amountField: "depositRefundAmount",
    fields: [
      { key: "customerName", label: "客户名称", required: true },
      { key: "returnReason", label: "退租原因", type: "textarea", span: 2, rows: 3, required: true },
      { key: "returnQuantity", label: "退租数量", type: "number", required: true },
      { key: "assetCodes", label: "退租电池编码", type: "textarea", span: 2, rows: 3, required: true },
      { key: "inspectionResult", label: "技术验收结论", type: "textarea", span: 2, rows: 3 },
      { key: "damageClaimAmount", label: "损坏索赔金额", type: "number" },
      { key: "depositRefundAmount", label: "押金退还金额", type: "number" },
    ],
    nodes: [
      { name: "业务发起", operator: "申请人" },
      { name: "技术部审核", operator: "技术部" },
      { name: "彭总审批", operator: "彭总" },
      { name: "固定资产管理员回收入库", operator: "资产管理员" },
      { name: "财务协同对账记账", operator: "财务" },
    ],
    riskItems: ["退租必须完成电池验收并判断是否损坏。", "押金退还或索赔金额需同步财务。"],
    requiredAttachments: ["退租申请", "验收照片", "押金记录"],
  },
  {
    key: "CUSTOMER_BUYOUT",
    label: "客户买断审批",
    source: "《延成公司业务流程》客户买断申请流程",
    defaultApplicant: "刘销售",
    defaultDepartment: "销售部",
    defaultTitle: "客户买断申请",
    defaultSummary: "业务发起买断申请，财务审核买断数量、价格和金额，资产系统出库。",
    customerField: "customerName",
    amountField: "buyoutAmount",
    fields: [
      { key: "customerName", label: "客户名称", required: true },
      { key: "buyoutType", label: "买断类型", type: "select", options: ["未到期买断", "到期买断"], required: true },
      { key: "agreementNo", label: "买断协议编号" },
      { key: "assetCodes", label: "买断电池编码", type: "textarea", span: 2, rows: 3, required: true },
      { key: "buyoutQuantity", label: "买断数量", type: "number", required: true },
      { key: "unitPrice", label: "买断单价", type: "number", required: true },
      { key: "buyoutAmount", label: "买断金额", type: "number", required: true },
    ],
    nodes: [
      { name: "业务发起", operator: "申请人" },
      { name: "财务审批", operator: "赵财务" },
      { name: "彭总审批", operator: "彭总" },
      { name: "固定资产管理员出库", operator: "资产管理员" },
      { name: "财务协同对账记账", operator: "财务" },
    ],
    riskItems: ["买断数量、价格和金额需按合同或买断协议审核。", "审批通过后需更改电池状态为买断出库。"],
    requiredAttachments: ["原合同", "买断协议", "客户确认记录"],
  },
  {
    key: "WARRANTY_SCRAP",
    label: "质保期内电池报废",
    source: "《延成公司业务流程》质保期内质量原因导致电池报废审批流程",
    defaultApplicant: "赵工",
    defaultDepartment: "技术部",
    defaultTitle: "质保期内电池报废申请",
    defaultSummary: "技术确认质保期内报废原因、厂商解决方案和赔偿标准。",
    customerField: "supplierName",
    amountField: "compensationAmount",
    fields: [
      { key: "supplierName", label: "上游厂商", required: true },
      { key: "assetCode", label: "报废电池编码/BT码", required: true },
      { key: "scrapReason", label: "报废原因", type: "textarea", span: 2, rows: 3, required: true },
      { key: "warrantyConfirmed", label: "质保期内确认", type: "select", options: yesNoOptions, required: true },
      { key: "solution", label: "厂商解决方案", type: "select", options: ["报废赔偿", "免费换新"], required: true },
      { key: "compensationAmount", label: "赔偿金额", type: "number" },
      { key: "newAssetInfo", label: "换新电池信息", type: "textarea", span: 2, rows: 2 },
    ],
    nodes: [
      { name: "技术部发起", operator: "申请人" },
      { name: "采购签订赔偿/换新协议", operator: "采购" },
      { name: "财务审核协议", operator: "赵财务" },
      { name: "彭总审批", operator: "彭总" },
      { name: "财务/固定资产执行", operator: "财务/资产" },
    ],
    riskItems: ["需与上游厂商确认质保期内报废。", "旧电池退回上游或注销库存、新电池入库必须闭环。"],
    requiredAttachments: ["质保确认", "检测报告", "赔偿或换新协议"],
  },
  {
    key: "USED_BATTERY_DISPOSAL",
    label: "废旧电池处置",
    source: "《延成公司业务流程》废旧电池处置申请审批流",
    defaultApplicant: "王库管",
    defaultDepartment: "资产管理部",
    defaultTitle: "废旧电池处置申请",
    defaultSummary: "资产管理员根据盘点清单发起废旧电池处置申请，技术审核状态和循环次数。",
    businessNoField: "inventoryListNo",
    amountField: "saleAmount",
    fields: [
      { key: "inventoryListNo", label: "资产盘点清单号", required: true },
      { key: "batteryScope", label: "处置电池范围", type: "textarea", span: 2, rows: 3, required: true },
      { key: "batteryStatus", label: "电池状态", type: "select", options: batteryStatusOptions, required: true },
      { key: "cycleCount", label: "循环次数", type: "number" },
      { key: "buyerName", label: "售卖/处置对象" },
      { key: "saleAmount", label: "售卖金额", type: "number" },
      { key: "disposalMethod", label: "处置方式", type: "select", options: disposalOptions, required: true },
    ],
    nodes: [
      { name: "资产管理员发起", operator: "申请人" },
      { name: "技术部审批", operator: "技术部" },
      { name: "采购审批并签售卖合同", operator: "采购" },
      { name: "资产管理员出库", operator: "资产管理员" },
      { name: "财务记账", operator: "财务" },
    ],
    riskItems: ["技术需审核电池状态和循环次数。", "售卖出库单需作为财务应收依据。"],
    requiredAttachments: ["资产盘点清单", "售卖合同", "售卖出库单"],
  },
  {
    key: "SEAL_USE",
    label: "用印申请",
    source: "《延成公司业务流程》用印审批流程",
    defaultApplicant: "行政专员",
    defaultDepartment: "行政人事部",
    defaultTitle: "用印申请",
    defaultSummary: "行政风控审核并根据文件涉及事项加签相关部门负责人。",
    customerField: "counterparty",
    businessNoField: "documentNo",
    fields: [
      { key: "documentName", label: "用印文件名称", required: true },
      { key: "documentNo", label: "合同/文件编号" },
      { key: "sealType", label: "印章类型", type: "select", options: ["公章", "合同章", "财务章", "法人章"], required: true },
      { key: "counterparty", label: "对方单位/用途对象" },
      { key: "involvedDepartment", label: "所涉部门", required: true },
      { key: "copies", label: "用印份数", type: "number", required: true, defaultValue: 1 },
      { key: "reason", label: "用印原因", type: "textarea", span: 2, rows: 3, required: true },
    ],
    nodes: [
      { name: "发起人", operator: "申请人" },
      { name: "行政风控审批并加签", operator: "行政风控" },
      { name: "所涉部门负责人审批", operator: "部门负责人" },
      { name: "刘少鹏审批", operator: "刘少鹏" },
      { name: "彭总审批", operator: "彭总" },
      { name: "行政协同用印", operator: "行政" },
    ],
    riskItems: ["用印需明确所涉部门，行政风控按事项加签。"],
    requiredAttachments: ["待用印文件", "合同审批记录"],
  },
  {
    key: "BUSINESS_TRIP",
    label: "公出申请",
    source: "《延成公司业务流程》公出申请单",
    defaultApplicant: "申请人",
    defaultDepartment: "业务部",
    defaultTitle: "公出申请",
    defaultSummary: "员工公出需部门负责人、刘少鹏和彭总审批，审批后进入人事考勤计算。",
    amountField: "budgetAmount",
    fields: [
      { key: "tripReason", label: "公出事由", type: "textarea", span: 2, rows: 3, required: true },
      { key: "destination", label: "公出地点", required: true },
      { key: "startTime", label: "开始时间", type: "datetime", required: true },
      { key: "endTime", label: "结束时间", type: "datetime", required: true },
      { key: "transport", label: "交通方式" },
      { key: "budgetAmount", label: "费用预算", type: "number" },
    ],
    nodes: [
      { name: "申请人", operator: "申请人" },
      { name: "部门负责人审批", operator: "部门负责人" },
      { name: "刘少鹏审批", operator: "刘少鹏" },
      { name: "彭总审批", operator: "彭总" },
      { name: "人事考勤计算", operator: "行政人事" },
    ],
    riskItems: ["公出结束后人事需据审批记录计算考勤。"],
  },
  {
    key: "REIMBURSEMENT",
    label: "报销流程",
    source: "《延成公司业务流程》报销审批流程",
    defaultApplicant: "申请人",
    defaultDepartment: "财务部",
    defaultTitle: "费用报销申请",
    defaultSummary: "财务专员审核票据，财务负责人复核后进入管理层审批和出纳付款。",
    amountField: "reimburseAmount",
    fields: [
      { key: "expenseType", label: "报销类型", required: true },
      { key: "expenseOwner", label: "费用归属", required: true },
      { key: "reimburseAmount", label: "报销金额", type: "number", required: true },
      { key: "invoiceCount", label: "发票张数", type: "number" },
      { key: "payeeAccount", label: "收款账户", type: "textarea", span: 2, rows: 2, required: true },
      { key: "expenseDetails", label: "报销明细", type: "textarea", span: 2, rows: 4, required: true },
    ],
    nodes: [
      { name: "申请人", operator: "申请人" },
      { name: "财务专员审核", operator: "财务专员" },
      { name: "财务负责人复核", operator: "财务负责人" },
      { name: "刘少鹏审批", operator: "刘少鹏" },
      { name: "彭总审批", operator: "彭总" },
      { name: "出纳付款", operator: "出纳" },
    ],
    riskItems: ["财务需审核报销凭证、费用归属和是否属于我方承担。"],
    requiredAttachments: ["发票", "报销凭证", "费用说明"],
  },
  {
    key: "LOAN",
    label: "借款申请",
    source: "《延成公司业务流程》借款审批单",
    defaultApplicant: "申请人",
    defaultDepartment: "业务部",
    defaultTitle: "借款申请",
    defaultSummary: "借款申请由财务、刘少鹏和彭总审批，通过后出纳付款。",
    amountField: "loanAmount",
    fields: [
      { key: "loanReason", label: "借款事由", type: "textarea", span: 2, rows: 3, required: true },
      { key: "loanAmount", label: "借款金额", type: "number", required: true },
      { key: "returnDate", label: "预计归还日期", type: "date", required: true },
      { key: "projectName", label: "关联项目/客户" },
      { key: "payeeAccount", label: "收款账户", type: "textarea", span: 2, rows: 2, required: true },
    ],
    nodes: [
      { name: "发起人", operator: "申请人" },
      { name: "财务审批", operator: "赵财务" },
      { name: "刘少鹏审批", operator: "刘少鹏" },
      { name: "彭总审批", operator: "彭总" },
      { name: "出纳付款", operator: "出纳" },
    ],
    riskItems: ["借款需明确预计归还日期和费用归属。"],
    requiredAttachments: ["借款说明", "收款账户确认"],
  },
  {
    key: "LEAVE_REQUEST",
    label: "请假申请",
    source: "《延成公司业务流程》请假审批单",
    defaultApplicant: "申请人",
    defaultDepartment: "业务部",
    defaultTitle: "请假申请",
    defaultSummary: "请假申请经部门负责人、刘少鹏和彭总审批后，由行政人事处理。",
    fields: [
      { key: "leaveType", label: "请假类型", type: "select", options: ["事假", "病假", "年假", "调休", "婚假", "产假", "其他"], required: true },
      { key: "startTime", label: "开始时间", type: "datetime", required: true },
      { key: "endTime", label: "结束时间", type: "datetime", required: true },
      { key: "days", label: "请假天数", type: "number", required: true },
      { key: "handoverPerson", label: "工作交接人" },
      { key: "reason", label: "请假事由", type: "textarea", span: 2, rows: 3, required: true },
    ],
    nodes: [
      { name: "发起人", operator: "申请人" },
      { name: "部门负责人审批", operator: "部门负责人" },
      { name: "刘少鹏审批", operator: "刘少鹏" },
      { name: "彭总审批", operator: "彭总" },
      { name: "行政人事", operator: "行政人事" },
    ],
    riskItems: ["审批通过后由行政人事同步考勤。"],
  },
];
